admin_school/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from auths import views as auths_view


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', auths_view.home, name='home'),
    path('auths/', include('auths.urls', namespace='auths')),
    path('stats/', include('stats.urls', namespace='stats')),
    path('blog/', include('blog.urls', namespace='blog')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

auths/urls.py
from django.urls import path
from . import views, ajax_view, n_teaching, student_views

app_name = 'auths'

urlpatterns = [
    path('signup/', views.user_signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('create_teacher_profile/', views.create_teacher_profile, name='create_teacher_profile'),
    path('update_teacher_profile/', views.update_teacher_profile, name='update_teacher_profile'),
    path('add_files/', views.add_files, name='add_files'),
    path('display_teacher_profile/', views.display_teacher_profile, name='display_teacher_profile'),
    path('teacher_docs/', views.teacher_docs, name='teacher_docs'),
    path('create_non_teacher_profile/', n_teaching.create_non_teacher_profile, name='create_non_teacher_profile'),
    path('display_non_teacher_profile/', n_teaching.display_non_teacher_profile, name='display_non_teacher_profile'),
    path('update_non_teacher_profile/', n_teaching.update_non_teacher_profile, name='update_non_teacher_profile'),
    path('non_teacher_docs/', n_teaching.non_teacher_docs, name='non_teacher_docs'),
    path('create_student_profile/', student_views.create_student_profile, name='create_student_profile'),
    path('display_student_profile/', student_views.display_student_profile, name='display_student_profile'),
    path('update_student_profile/', student_views.update_student_profile, name='update_student_profile'),
    path('get_school_by_zone/', ajax_view.get_school_by_zone, name='get_school_by_zone'),
    path('get_student_by_school/', ajax_view.get_student_by_school, name='get_student_by_school'),
    path('get_teachers_by_school/', views.get_teachers_by_school, name='get_teachers_by_school'),
    path('render_pdf_view/', views.render_pdf_view, name='render_pdf_view'),
    path('n_render_pdf_view/', n_teaching.render_pdf_view, name='n_render_pdf_view'),
    path('teaching_staff_list/', views.teaching_staff_list, name='teaching_staff_list'),
    path('user_profile/<int:id>/', views.user_profile, name='user_profile'),
    path('students_list/', student_views.students_list, name='students_list'),
    path('student_profile/<int:id>/', student_views.student_profile, name='student_profile'),
    path('summary_dashboard/', views.summary_dashboard, name='summary_dashboard'),
    path('get_follow/', views.UserFollow.as_view(), name='get_follow'),
    path('follow_status/', views.UserFollowStatus.as_view(), name='follow_status'),
]

blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('create_post/', views.CreatePost.as_view(), name='create_post'),
    path('followers_count/', views.followers_count, name='followers_count'),
    path('index/', views.index, name='index'),
]

auths/views.py
from django.contrib import messages
from django.contrib.auth import get_user_model, authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.core.files.storage import FileSystemStorage
from django.core.paginator import Paginator
from django.db import transaction
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import get_template, render_to_string
from django.views import View
from xhtml2pdf import pisa
from .models import Zone, School, TeachingSTaff, TeachingSTaffFiles, Subject, Student, StudentFiles, NonTeachingSTaffFiles
from blog.models import Follow, Stream, Post
User = get_user_model()


def home(request):
    return render(request, 'auths/login.html')


def user_signup(request):
    if request.method == 'POST':
        username = request.POST['username']
        email = request.POST['email']
        first_name = request.POST['first_name']
        last_name = request.POST['last_name']
        file_no = request.POST['file_no']
        status = request.POST['status']
        password = request.POST['password']
        password2 = request.POST['password2']

        # validate username
        check_users = ['admin', 'css', 'js', 'authenticate', 'login', 'logout', 'administrator', 'root', 'email',
                       'user', 'join', 'sql', 'static', 'python', 'delete', 'sex', 'sexy']

        if username in check_users:
            messages.error(request, 'Your Username, ' + username + ', Is Not Acceptable. Please Use Another Username')
            return render(request, 'auths/user_signup.html')

        if User.objects.filter(username=username).exists():
            messages.error(request, 'Your Username, ' + username + ', Already Exists. Please Try Another Username')
            return render(request, 'auths/user_signup.html')

        # validate email
        email = email.strip().lower()
        if ("@" not in email) or (email[-4:] not in ".com.org.edu.gov.net"):
            messages.error(request, 'Your Email, ' + email + ', Is Invalid!!!')
            return render(request, 'auths/user_signup.html')
        if User.objects.filter(email=email).exists():
            messages.error(request, 'Your Email, ' + email + ', Already Exists. Please Try Another Email')
            return render(request, 'auths/user_signup.html')

        if User.objects.filter(file_no=file_no).exists():
            messages.error(request,
                           'Your File Number, ' + file_no + ', Already Exists. Please Enter Correct File Number')
            return render(request, 'auths/user_signup.html')

        # validate password
        if password != password2:
            messages.error(request, "Your Passwords Don't match")
            return render(request, 'auths/user_signup.html')

        User.objects.create_user(username=username, password=password, email=email, first_name=first_name,
                                 last_name=last_name,
                                 status=status, file_no=file_no)
        user = User.objects.get(username=username)

        context = {
            'username': username, 'email': email, 'first_name': first_name, 'last_name': last_name, 'status': status,
            'file_no': file_no, 'unique_id': user.unique_id
        }
        return render(request, 'auths/signup_success.html', context)
    return render(request, 'auths/user_signup.html')


# login view
def user_login(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        if not User.objects.filter(username=username).exists():
            messages.error(request, 'This Username, ' + username + ', Does Not Exist...')
            return render(request, 'auths/login.html')
        else:
            user = authenticate(request, username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    if request.user.is_superuser:
                        return redirect('/auths/display_teacher_profile/')
                    elif request.user.status == 'administrator':
                        return redirect('/auths/display_teacher_profile/')
                    elif request.user.status == 'staff - teaching':
                        return redirect('/auths/display_teacher_profile/')
                    elif request.user.status == 'staff - non-teaching':
                        return redirect('/auths/display_non_teacher_profile/')
                    elif request.user.status == 'student':
                        return redirect('/auths/display_student_profile/')
            else:
                messages.error(request, 'Username or password incorrect!!!')
                return render(request, 'auths/login.html')

    return render(request, 'auths/login.html')


# logout view
@login_required
def user_logout(request):
    logout(request)
    return render(request, 'auths/login.html')


@login_required
def create_teacher_profile(request):
    all_zones = Zone.objects.order_by('name')
    all_schools = School.objects.order_by('zone')
    all_subjects = Subject.objects.order_by('name')
    context = {
        'all_zones': all_zones,
        'all_schools': all_schools,
        'all_subjects': all_subjects
    }

    if request.method == 'POST':
        # get all data
        title = request.POST['title']
        middle_name = request.POST['middle_name']
        gender = request.POST['gender']
        date_of_birth = request.POST['date_of_birth']
        age = request.POST['age']
        address = request.POST['address']
        religion = request.POST['religion']
        phone_number = request.POST['phone_number']
        picture = request.FILES['picture']
        about_me = request.POST['about_me']
        designation = request.POST['designation']
        grade_level = request.POST['grade_level']
        first_appointment = request.POST['first_appointment']
        years_in_service = request.POST['years_in_service']
        qualification = request.POST['qualification']
        discipline = request.POST['discipline']
        current_posting_zone_id = request.POST['current_posting_zone']
        current_posting_school_id = request.POST['current_posting_school']
        published_work = request.POST['published_work']
        current_subject_id = request.POST['current_subject']
        previous_posting_1_id = request.POST['previous_posting_1']
        previous_posting_2_id = request.POST['previous_posting_2']
        previous_posting_3_id = request.POST['previous_posting_3']
        other_subject_id = request.POST['other_subject']

        if previous_posting_1_id == 'Not Available':
            previous_posting_1 = None
        else:
            previous_posting_1 = School.objects.get(id=previous_posting_1_id)

        if previous_posting_2_id == 'Not Available':
            previous_posting_2 = None
        else:
            previous_posting_2 = School.objects.get(id=previous_posting_2_id)

        if previous_posting_3_id == 'Not Available':
            previous_posting_3 = None
        else:
            previous_posting_3 = School.objects.get(id=previous_posting_3_id)

        current_subject = Subject.objects.get(id=current_subject_id)
        current_posting_zone = Zone.objects.get(id=current_posting_zone_id)
        current_posting_school = School.objects.get(id=current_posting_school_id)
        other_subject = Subject.objects.get(id=other_subject_id)

        teacher = TeachingSTaff.objects.get(user=request.user)
        teacher.title = title
        teacher.middle_name = middle_name
        teacher.picture = picture
        teacher.gender = gender
        teacher.date_of_birth = date_of_birth
        teacher.age = age
        teacher.address = address
        teacher.religion = religion
        teacher.phone_number = phone_number
        teacher.about_me = about_me
        teacher.designation = designation
        teacher.grade_level = grade_level
        teacher.first_appointment = first_appointment
        teacher.years_in_service = years_in_service
        teacher.qualification = qualification
        teacher.discipline = discipline
        teacher.published_work = published_work
        teacher.current_posting_zone = current_posting_zone
        teacher.current_posting_school = current_posting_school
        teacher.previous_posting_1 = previous_posting_1
        teacher.previous_posting_2 = previous_posting_2
        teacher.previous_posting_3 = previous_posting_3
        teacher.current_subject = current_subject
        teacher.other_subject = other_subject
        teacher.save()

        images = request.FILES.getlist('documents')
        document_title = request.POST.getlist('document_title[]')
        # print(document_title, type(document_title))
        file_list = []
        for image in images:
            fs = FileSystemStorage()
            file_path = fs.save(image.name, image)
            file_list.append(file_path)

        # print(file_list, type(file_list))
        for key, value in zip(document_title, file_list):
            teacher_files = TeachingSTaffFiles(user=teacher, document_title=key, documents=value)
            teacher_files.save()
        return redirect('/auths/display_teacher_profile/')

    return render(request, 'auths/create_teacher_profile.html', context)


def add_files(request):
    if request.user.status == 'administrator' or request.user.status == 'staff - teaching':
        teacher = TeachingSTaff.objects.get(user=request.user)
        images = request.FILES.getlist('documents')
        document_title = request.POST.getlist('document_title[]')
        # print(document_title, type(document_title))
        file_list = []
        for image in images:
            fs = FileSystemStorage()
            file_path = fs.save(image.name, image)

auths/templates/auths/login.html
{% extends 'auths/reg_base.html' %}
{% load static %}

{% block title %}Education | Login Page{% endblock title %}

{% block reg_content %}
    <section class="sign-in">
        <div class="container">
            <div class="signin-content">
                <div class="signin-image">
                    <figure><img src="{% static 'img/signin.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'auths:signup' %}" class="signup-image-link">Create an account</a>
                </div>
                <div class="signin-form">
                    <h2 class="form-title">Login</h2>
                    <form class="register-form" id="login-form" method="post">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="">
                                <input name="username" type="text" placeholder="Your Username" class="form-control input-height" />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="">
                                <input name="password" type="password" placeholder="Your Password" class="form-control input-height" />
                            </div>
                        </div>
                        <div class="form-group">
                            <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />
                            <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>
                        </div>
                        <div class="form-group form-button">
                            <button type="submit" class="btn btn-round btn-primary" name="signin" id="signin">Login</button>
                        </div>
                    </form>
                    <div class="social-login">
                        <span class="social-label">Or login with</span>
                        <ul class="socials">
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-facebook"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-twitter"></i></a></li>
                            <li><a href="#"><i class="display-flex-center zmdi zmdi-google"></i></a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock reg_content %}

auths/templates/auths/reg_base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta content="width=device-width, initial-scale=1" name="viewport" />
	<meta name="description" content="Responsive Admin Template" />
	<meta name="author" content="RedstarHospital" />
	<title>{% block title %}{% endblock title %}</title>
	<!-- google font -->
	<link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
	<!-- icons -->
	<link rel="stylesheet" href="{% static 'css/material-design-iconic-font.min.css' %}">
	<!-- bootstrap -->
	<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" />
	<!-- Theme Styles -->
	<link href="{% static 'css/theme-style.css' %}" rel="stylesheet" id="rt_style_components" type="text/css" />
    <link href="{% static 'css/formlayout.css' %}" rel="stylesheet" type="text/css" />
	<!-- style -->
	<link rel="stylesheet" href="{% static 'css/page-login.css' %}">
	<!-- favicon -->
	<link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" />
</head>
<body>
    <div class="main">
		<!-- Sign up form -->
        {% block reg_content %}
		
        {% endblock reg_content %}
	</div>

    <script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/togglePassword.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

auths/templates/auths/school_by_zone.html
{% for school in data %}
    <option value="{{ school.id }}">{{ school.name }} | {{ school.zone }}</option>
{% endfor %}

auths/templates/auths/signup_success.html
{% extends 'auths/reg_base.html' %}
{% load static %}

{% block title %}Education | Signup Success Page{% endblock title %}

{% block reg_content %}
    <section class="sign-in">
        <div>
            <h3>
                Thank You, {{ first_name }} {{ last_name }}.<br>
                You Have Successfully Registered. Below Are Your Registration Details:
            </h3>
        </div>
        <div>
            <h2>Username: {{ username }}</h2>
            <h2>Email: {{ email }}</h2>
            <h2>First Name: {{ first_name }}</h2>
            <h2>Surname: {{ last_name }}</h2>
            <h2>User Status: {{ status }}</h2>
            <h2>File Number: {{ file_no }}</h2>
            <h2>Unique ID: {{ unique_id }}</h2>
        </div>
        <p>Already Registerd?</p>
        <div class="form-group form-button">
            <button class="btn btn-round btn-primary">
                <a href="{% url 'auths:login' %}" class="signup-image-link">Login</a>
            </button>
        </div>
    </section>
{% endblock reg_content %}

auths/templates/auths/student_list.html
{% extends 'auths/base.html' %}
{% load static %}

{% block title %}Education | Student Dashboard{% endblock title %}

{% block bootstrap_table_css %}
    <link href="{% static 'css/datatable.bootstrap5.min.css' %}" rel="stylesheet" type="text/css" />
{% endblock bootstrap_table_css %}

{% block page_content %}
    <!-- start page content -->
    <div class="page-content-wrapper">
				<div class="page-content">
					<div class="page-bar">
						<div class="page-title-breadcrumb">
							<div class=" pull-left">
								<div class="page-title">All Students List</div>
							</div>
							<ol class="breadcrumb page-breadcrumb pull-right">
								<li><i class="fa fa-home"></i>&nbsp;<a class="parent-item"
										href="index.html">Home</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li><a class="parent-item" href="">Professors</a>&nbsp;<i class="fa fa-angle-right"></i>
								</li>
								<li class="active">Students List</li>
							</ol>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="card">
                                <div class="card-head">
                                    <header>List Of Students By Students</header>
                                    <form method="POST" class="register-form" id="register-form">
                                        <div class="form-group">
                                            <label style="float: center;">Name Of School:</label>
                                            <select class="form-select" name="current_school" id="current_school" required>
                                                {% for school in all_schools %}
                                                    <option value="{{ school.id }}">{{ school.name }} | {{ school.zone }}</option>
                                                {% endfor %}
                                            </select>
                                        </div>
                                    </form>
                                </div>
                                
                                <div class="card-body">
                                    <div class="row">
                                        <div class="col-sm-12">
                                            <table class="table table-striped">
                                                <thead>
                                                    <th>S/No</th>
                                                    <th>Name</th>
                                                    <th>Admission Number</th>
                                                    <th>School</th>
                                                    <th>Department</th>
                                                    <th>Class</th>
                                                    <th>Gender</th>
                                                    <th>Age</th>
                                                </thead>
                                                <tbody class="table_body">
                                                
                                                </tbody>
                                            </table>
                                        </div>
                                    </div>
                                    <div class="row">
                                        <div class="col-sm-12 col-md-7">
                                            <div>
                                                <ul class="pagination">
                                                    {% if teachers.has_previous %}
                                                    <li class="paginate_button page-item previous" id="example1_previous">
                                                        <a href="?page={{ teachers.previous_page_number }}" aria-controls="example1" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                                                    </li>
                                                    {% endif %}
                                                    <li class="paginate_button page-item active">
                                                        Page {{ teachers.number }} of {{ teachers.paginator.num_pages }}.
                                                        <!--<a href="#" aria-controls="example1" data-dt-idx="1" tabindex="0" class="page-link">1</a>-->
                                                    </li>
                                                    {% if teachers.has_next %}
                                                    <li class="paginate_button page-item next" id="example1_next">
                                                        <a href="?page={{ teachers.next_page_number }}" aria-controls="example1" data-dt-idx="2" tabindex="0" class="page-link">Next</a>
                                                    </li>
                                                    {% endif %}
                                                </ul>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
						</div>
					</div>
				</div>
			</div>
    <!-- end page content -->
{% endblock page_content %}

{% block bootstrap_table_js %}
    <script src="{% static 'js/jquery.datatables.min.js' %}"></script>
    <script src="{% static 'js/datatables-bootstrap5.min.js' %}"></script>
    <script src="{% static 'js/tabledata.js' %}"></script>
{% endblock bootstrap_table_js %}

auths/templates/auths/students_by_school.html
{% for student in data %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ student.user.first_name }} {{ student.user.last_name }}</td>
        <td>{{ student.user.file_no }}</td>
        <td>{{ student.current_school }}</td>
        <td>{{ student.department }}</td>
        <td>{{ student.std_class }} {{ student.level }}</td>
        <td>{{ student.gender }}</td>
        <td>{{ student.age }}</td>
        <td>
            <button id="addRow" class="btn btn-info">
                <a href="{% url 'auths:student_profile' student.user.id %}">View</a>
            </button>
        </td>
    </tr>
{% endfor %}

auths/templates/auths/teachers_by_school.html
{% for teacher in data %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ teacher.user.first_name }} {{ teacher.user.last_name }}</td>
        <td>{{ teacher.user.file_no }}</td>
        <td>{{ teacher.designation }}</td>
        <td>{{ teacher.grade_level }}</td>
        <td>{{ teacher.user.email }}</td>
        <td>{{ teacher.phone_number }}</td>
        <td>{{ teacher.age }}</td>
        <td>
            <button id="addRow" class="btn btn-info">
                <a href="{% url 'auths:user_profile' teacher.user.id %}">View</a>
            </button>
        </td>
    </tr>
{% endfor %}

auths/templates/auths/user_signup.html
{% extends 'auths/reg_base.html' %}
{% load static %}

{% block title %}Education | Signup Page{% endblock title %}

{% block reg_content %}
    <section class="signup">
        <div id="form-messages">
            {% if messages %}
                {% for message in messages %}
                    <h3 style="text-align: center; background: red; color: white;">{{ message }}</h3>
                {% endfor %}
            {% endif %}
        </div>
        <div class="container">
            <div class="signup-content">
                <div class="signup-form">
                    <h2 class="form-title">Sign up</h2>
                    <form method="POST" class="register-form" id="register-form">
                        {% csrf_token %}
                        <div class="form-group">
                            <div class="">
                                <input name="username" type="text" placeholder="Your Username" class="form-control input-height" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="">
                                <input name="email" type="email" placeholder="Your Email" class="form-control input-height" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="">
                                <input name="first_name" type="text" placeholder="Your First Name" class="form-control input-height" required />
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="">
                                <input name="last_name" type="text" placeholder="Your Surname" class="form-control input-height" required />
                            </div>
                        </div>
       
                        <div class="form-group">
                            <label>What is your status?</label>
                            <select class="form-select" name="status" required>
                                <option value="administrator">Administrator</option>
                                <option value="staff - teaching">Teaching Staff</option>
                                <option value="staff - non-teaching">Non-Teaching Staff</option>
                                <option value="student">Student</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control input-height" name="file_no" placeholder="Your File Number (Admission Number For Students)" required>
                        </div>
                        <div class="form-group">
                            <div class="">
                                <input name="password" type="password" placeholder="Password" class="form-control input-height" required />
                            </div>
                            <div>
                                <label class="switchToggle">
                                    <input type="checkbox">
                                    <span class="slider green round" onclick="showPassword()"></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="">
                                <input name="password2" type="password" placeholder="Repeat Password" class="form-control input-height" required />
                            </div>
                            <div>
                                <label class="switchToggle">
                                    <input type="checkbox">
                                    <span class="slider green round" onclick="showPassword2()"></span>
                                </label>
                            </div>
                        </div>
                        <div class="form-group form-button">
                            <button type="submit" class="btn btn-round btn-primary" name="signup" id="register">Register</button>
                        </div>
                    </form>
                </div>
                <div class="signup-image">
                    <figure><img src="{% static 'img/signup.jpg' %}" alt="sing up image"></figure>
                    <a href="{% url 'auths:login' %}" class="signup-image-link">I am already member</a>
                </div>
            </div>
        </div>
    </section>
{% endblock reg_content %}